development:
  adapter: postgresql
  encoding: unicode
  database: tutu2_development
  pool: 5
  username: tutu2
  password: '!111223@'

test:
  adapter: postgresql
  encoding: unicode
  database: tutu2_test
  pool: 5
  username: tutu2
  password: '!111223@'

production:
  adapter: postgresql
  encoding: unicode
  database: tutu2_production
  pool: 5